import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mkdir, mkdtemp, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { buildProgram } from '../src/cli.js';

let tmp: string;
let homeDir: string;
let assetsDir: string;
let originalAssetsEnv: string | undefined;
let originalExitCode: number | string | null | undefined;

beforeEach(async () => {
  tmp = await mkdtemp(path.join(os.tmpdir(), 'hive-cli-'));
  homeDir = path.join(tmp, 'home');
  assetsDir = path.join(tmp, 'assets');
  await mkdir(homeDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });
  await writeFile(
    path.join(assetsDir, 'manifest.json'),
    JSON.stringify({ generatedAt: new Date(0).toISOString(), hiveCommit: 'test', skills: [], files: [] }),
  );
  originalAssetsEnv = process.env.HIVE_SKILLS_ASSETS;
  process.env.HIVE_SKILLS_ASSETS = assetsDir;
  originalExitCode = process.exitCode;
});

afterEach(async () => {
  await rm(tmp, { recursive: true, force: true });
  if (originalAssetsEnv === undefined) delete process.env.HIVE_SKILLS_ASSETS;
  else process.env.HIVE_SKILLS_ASSETS = originalAssetsEnv;
  // Every command adapter sets process.exitCode as a side effect; reset
  // it after each test so a test exercising a failure path never leaks
  // a nonzero code into the overall `vitest run` process exit status.
  process.exitCode = originalExitCode;
});

function argv(...args: string[]): string[] {
  return ['node', 'hive-skills', ...args];
}

describe('buildProgram: wiring', () => {
  it('registers all 7 subcommands plus the default (wizard) action', () => {
    const program = buildProgram();
    const names = program.commands.map((c) => c.name()).sort();
    expect(names).toEqual(['backup', 'doctor', 'install', 'list', 'propose', 'restore', 'scan']);
  });

  it('carries the version from version.ts', () => {
    const program = buildProgram();
    expect(program.version()).toBe('0.1.0');
  });

  it('declares every global option', () => {
    const program = buildProgram();
    const flags = program.options.map((o) => o.long).sort();
    expect(flags).toEqual(
      ['--dry-run', '--force', '--home', '--json', '--no-backup', '--project', '--registry', '--version', '--yes'].sort(),
    );
  });
});

describe('buildProgram: scan --json', () => {
  it('runs against a fixture --home and prints valid JSON with the expected shape', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      const program = buildProgram();
      await program.parseAsync(argv('scan', '--json', '--home', homeDir));
      expect(logSpy).toHaveBeenCalledTimes(1);
      const parsed = JSON.parse(logSpy.mock.calls[0]![0] as string);
      expect(parsed).toHaveProperty('clients');
      expect(Array.isArray(parsed.clients)).toBe(true);
      const claudeCode = parsed.clients.find((c: { id: string }) => c.id === 'claude-code');
      expect(claudeCode.detected).toBe(true);
    } finally {
      logSpy.mockRestore();
    }
  });
});

describe('buildProgram: install --yes', () => {
  it('installs a bundled skill for real and reports it', async () => {
    // Build a real catalog with one skill in this test's fixture assets dir.
    const composableDir = path.join(assetsDir, 'skills', 'authored', 'foo', 'composable');
    await mkdir(path.join(composableDir, 'mini'), { recursive: true });
    await writeFile(path.join(composableDir, 'INDEX.md'), '# foo\n\nA test skill.\n');
    await writeFile(path.join(composableDir, 'mini', '00-core.md'), 'core');
    await writeFile(path.join(composableDir, 'BUNDLE.md'), '<!-- GENERATED by tools/hive.py compile. Do not hand-edit. -->\nx\n');
    await writeFile(path.join(composableDir, 'VERSION'), '1.0.0');
    await writeFile(
      path.join(assetsDir, 'manifest.json'),
      JSON.stringify({
        generatedAt: new Date(0).toISOString(),
        hiveCommit: 'test',
        skills: [
          {
            name: 'foo',
            category: 'authored',
            version: '1.0.0',
            minis: 1,
            bundleTokens: 5,
            description: 'A test skill.',
            path: 'skills/authored/foo',
          },
        ],
        files: [],
      }),
    );

    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      const program = buildProgram();
      await program.parseAsync(
        argv('install', '--client', 'claude-code', '--skill', 'foo', '--yes', '--home', homeDir),
      );
      expect((await stat(path.join(homeDir, '.claude', 'skills', 'hive-foo'))).isDirectory()).toBe(true);
    } finally {
      logSpy.mockRestore();
    }
  });

  it('exits nonzero with a friendly message when --yes is missing', async () => {
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    try {
      const program = buildProgram();
      await program.parseAsync(argv('install', '--client', 'claude-code', '--skill', 'foo', '--home', homeDir));
      expect(process.exitCode).toBe(1);
      expect(errorSpy).toHaveBeenCalled();
    } finally {
      errorSpy.mockRestore();
    }
  });
});

describe('buildProgram: doctor --json', () => {
  it('exits 0 on a healthy fixture home', async () => {
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      const program = buildProgram();
      await program.parseAsync(argv('doctor', '--json', '--home', homeDir));
      expect(process.exitCode).toBe(0);
      const parsed = JSON.parse(logSpy.mock.calls[0]![0] as string);
      expect(parsed).toHaveProperty('checks');
    } finally {
      logSpy.mockRestore();
    }
  });
});

describe('buildProgram: restore --list', () => {
  it('reports no backups on a fresh fixture home', async () => {
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    try {
      const program = buildProgram();
      await program.parseAsync(argv('restore', '--list', '--json', '--home', homeDir));
      const parsed = JSON.parse(logSpy.mock.calls[0]![0] as string);
      expect(parsed.backups).toEqual([]);
    } finally {
      logSpy.mockRestore();
    }
  });
});

describe('buildProgram: default action, non-TTY', () => {
  it('prints help and does not hang or throw when neither stdin nor stdout is a TTY', async () => {
    const stdinTtyBefore = process.stdin.isTTY;
    const stdoutTtyBefore = process.stdout.isTTY;
    // Test seam: force non-TTY regardless of the real harness running this suite.
    process.stdin.isTTY = false;
    process.stdout.isTTY = false;

    const helpSpy = vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
    try {
      const program = buildProgram();
      await program.parseAsync(argv('--home', homeDir));
      expect(helpSpy).toHaveBeenCalled();
      expect(process.exitCode ?? 0).toBe(0);
    } finally {
      helpSpy.mockRestore();
      process.stdin.isTTY = stdinTtyBefore;
      process.stdout.isTTY = stdoutTtyBefore;
    }
  });
});

describe('buildProgram: --help / --version do not crash the process', () => {
  it('--version throws a CommanderError (caught by main(), not process.exit) rather than exiting the test process', async () => {
    const program = buildProgram();
    await expect(program.parseAsync(argv('--version'))).rejects.toMatchObject({ code: 'commander.version' });
  });

  it('--help throws a CommanderError rather than exiting the test process', async () => {
    const program = buildProgram();
    await expect(program.parseAsync(argv('--help'))).rejects.toMatchObject({ code: 'commander.helpDisplayed' });
  });
});
