import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { resolveHomeContext } from '../src/core/paths.js';
import { CLIENT_REGISTRY } from '../src/core/registry.js';
import { loadCatalog, type Catalog } from '../src/core/catalog.js';
import { MANAGED_BLOCK_START } from '../src/core/pointer.js';
import { ConfirmationRequiredError, NothingToInstallError } from '../src/commands/errors.js';
import { formatInstallResult, resolveInstallSelection, runInstall } from '../src/commands/install.js';

let tmp: string;
let homeDir: string;
let assetsDir: string;

beforeEach(async () => {
  tmp = await mkdtemp(path.join(os.tmpdir(), 'hive-cmd-install-'));
  homeDir = path.join(tmp, 'home');
  assetsDir = path.join(tmp, 'assets');
  await mkdir(homeDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });
});

afterEach(async () => {
  await rm(tmp, { recursive: true, force: true });
});

function ctx() {
  return resolveHomeContext({ homeFlag: homeDir, platform: 'linux' });
}

async function makeCatalog(skillOpts: Array<{ category: string; name: string }>): Promise<Catalog> {
  const skills = [];
  for (const opts of skillOpts) {
    const composableDir = path.join(assetsDir, 'skills', opts.category, opts.name, 'composable');
    await mkdir(path.join(composableDir, 'mini'), { recursive: true });
    await writeFile(path.join(composableDir, 'INDEX.md'), `# ${opts.name}\n\nA test skill.\n`);
    await writeFile(path.join(composableDir, 'mini', '00-core.md'), 'core content');
    await writeFile(path.join(composableDir, 'BUNDLE.md'), '<!-- GENERATED by tools/hive.py compile. Do not hand-edit. -->\nbundle\n');
    await writeFile(path.join(composableDir, 'VERSION'), '1.0.0');
    skills.push({
      name: opts.name,
      category: opts.category,
      version: '1.0.0',
      minis: 1,
      bundleTokens: 10,
      description: 'A test skill.',
      path: `skills/${opts.category}/${opts.name}`,
    });
  }
  await writeFile(
    path.join(assetsDir, 'manifest.json'),
    JSON.stringify({ generatedAt: new Date(0).toISOString(), hiveCommit: 'test', skills, files: [] }),
  );
  return loadCatalog(assetsDir);
}

describe('resolveInstallSelection', () => {
  const detected = [
    { id: 'claude-code', detected: true, strategy: 'native-skills' },
    { id: 'codex', detected: false, strategy: 'native-skills' },
    { id: 'roo', detected: true, strategy: 'scan-only' },
  ];
  const catalog = { skills: [{ name: 'foo' }, { name: 'bar' }] } as unknown as Catalog;

  it('explicit --client/--skill win outright', () => {
    const sel = resolveInstallSelection({ clients: ['codex'], skills: ['foo'] }, detected, catalog);
    expect(sel).toEqual({ clients: ['codex'], skills: ['foo'] });
  });

  it('--all fills clients with detected, non-scan-only ids only', () => {
    const sel = resolveInstallSelection({ all: true }, detected, catalog);
    expect(sel.clients).toEqual(['claude-code']);
    expect(sel.skills).toEqual(['foo', 'bar']);
  });

  it('--client explicit + --all fills only skills (not clients)', () => {
    const sel = resolveInstallSelection({ clients: ['claude-code'], all: true }, detected, catalog);
    expect(sel).toEqual({ clients: ['claude-code'], skills: ['foo', 'bar'] });
  });

  it('neither explicit nor --all resolves to empty selections', () => {
    const sel = resolveInstallSelection({}, detected, catalog);
    expect(sel).toEqual({ clients: [], skills: [] });
  });
});

describe('runInstall', () => {
  it('throws NothingToInstallError when selection resolves empty', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await expect(runInstall(ctx(), CLIENT_REGISTRY, catalog, {})).rejects.toThrow(NothingToInstallError);
  });

  it('dry-run performs zero writes and reports wouldWrite entries, no --yes required', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const result = await runInstall(ctx(), CLIENT_REGISTRY, catalog, {
      clients: ['claude-code'],
      skills: ['foo'],
      dryRun: true,
    });
    expect(result.dryRun).toBe(true);
    if (result.dryRun) {
      expect(result.wouldWrite.length).toBe(3);
    }
    await expect(stat(path.join(homeDir, '.claude', 'skills', 'hive-foo'))).rejects.toThrow();
  });

  it('throws ConfirmationRequiredError for a real write without --yes', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await expect(
      runInstall(ctx(), CLIENT_REGISTRY, catalog, { clients: ['claude-code'], skills: ['foo'] }),
    ).rejects.toThrow(ConfirmationRequiredError);
  });

  it('installs for real with --yes', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const result = await runInstall(ctx(), CLIENT_REGISTRY, catalog, {
      clients: ['claude-code'],
      skills: ['foo'],
      yes: true,
    });
    expect(result.dryRun).toBe(false);
    if (!result.dryRun) {
      expect(result.result.performed.length).toBe(3);
      expect(result.result.backups.length).toBe(1);
    }
    expect((await stat(path.join(homeDir, '.claude', 'skills', 'hive-foo'))).isDirectory()).toBe(true);
  });

  it('with --yes but WITHOUT --write-pointers, rejects the pointer write (reject-all) and still installs the tree', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const result = await runInstall(ctx(), CLIENT_REGISTRY, catalog, {
      clients: ['gemini'],
      skills: ['foo'],
      yes: true,
    });
    expect(result.dryRun).toBe(false);
    if (!result.dryRun) {
      expect(result.result.skipped.some((a) => a.kind === 'write-pointer-block')).toBe(true);
    }
    await expect(stat(path.join(homeDir, '.gemini', 'GEMINI.md'))).rejects.toThrow();
    expect((await stat(path.join(homeDir, '.gemini', 'hive-skills', 'hive-foo'))).isDirectory()).toBe(true);
  });

  it('with --yes AND --write-pointers, approves the pointer write (approve-all)', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const result = await runInstall(ctx(), CLIENT_REGISTRY, catalog, {
      clients: ['gemini'],
      skills: ['foo'],
      yes: true,
      writePointers: true,
    });
    expect(result.dryRun).toBe(false);
    if (!result.dryRun) {
      expect(result.result.performed.some((a) => a.kind === 'write-pointer-block')).toBe(true);
    }
    const gemini = await readFile(path.join(homeDir, '.gemini', 'GEMINI.md'), 'utf8');
    expect(gemini).toContain(MANAGED_BLOCK_START);
  });

  it('--all with no clients detected throws NothingToInstallError', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await expect(runInstall(ctx(), CLIENT_REGISTRY, catalog, { all: true })).rejects.toThrow(NothingToInstallError);
  });
});

describe('formatInstallResult', () => {
  it('renders a dry-run plan preview', () => {
    const text = formatInstallResult({
      dryRun: true,
      plan: { actions: [] },
      wouldWrite: [{ kind: 'copy-tree', destPath: '/x/hive-foo' }],
    });
    expect(text).toContain('Dry run');
    expect(text).toContain('/x/hive-foo');
  });

  it('renders performed/skipped counts and a suggested snippet for a skipped pointer write', () => {
    const text = formatInstallResult({
      dryRun: false,
      plan: { actions: [] },
      result: {
        performed: [],
        skipped: [{ kind: 'write-pointer-block', clientId: 'gemini', destPath: '/x/GEMINI.md', block: '# >>> hive-skills >>>\nhello\n# <<< hive-skills <<<' }],
        backups: [],
        dryRun: false,
        wouldWrite: [],
      },
    });
    expect(text).toContain('Performed 0 write(s); skipped 1.');
    expect(text).toContain('Add this manually');
    expect(text).toContain('hive-skills >>>');
  });
});
