import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rm,
  stat,
  writeFile,
} from 'node:fs/promises';
import { createHash } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { resolveHomeContext } from '../src/core/paths.js';
import { CLIENT_REGISTRY } from '../src/core/registry.js';
import { loadCatalog, type Catalog } from '../src/core/catalog.js';
import { computeInstalledTreeHash, readInstallManifest } from '../src/core/installManifest.js';
import { restore } from '../src/core/backup.js';
import { MANAGED_BLOCK_START } from '../src/core/pointer.js';
import {
  executeInstall,
  planInstall,
  renderSkillShim,
  UnknownClientError,
  UnknownSkillError,
  UnsupportedClientError,
  type ExecutePorts,
} from '../src/core/installer.js';

let tmp: string;
let homeDir: string;
let assetsDir: string;

beforeEach(async () => {
  tmp = await mkdtemp(path.join(os.tmpdir(), 'hive-installer-'));
  homeDir = path.join(tmp, 'home');
  assetsDir = path.join(tmp, 'assets');
  await mkdir(homeDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });
});

afterEach(async () => {
  await rm(tmp, { recursive: true, force: true });
});

interface FixtureSkillOpts {
  category: string;
  name: string;
  version?: string;
  description?: string;
  coreContent?: string;
  /** Maps asset dir name (e.g. "scripts") -> { relFilePath: content }, mirroring a vendored source's non-.md dirs. */
  assetDirs?: Record<string, Record<string, string>>;
}

async function writeFixtureSkill(opts: FixtureSkillOpts) {
  const skillDir = path.join(assetsDir, 'skills', opts.category, opts.name);
  const composableDir = path.join(skillDir, 'composable');
  await mkdir(path.join(composableDir, 'mini'), { recursive: true });
  await writeFile(
    path.join(composableDir, 'INDEX.md'),
    `# ${opts.name}\n\n${opts.description ?? 'A test skill.'}\n`,
  );
  await writeFile(path.join(composableDir, 'mini', '00-core.md'), opts.coreContent ?? 'core content');
  await writeFile(
    path.join(composableDir, 'BUNDLE.md'),
    '<!-- GENERATED by tools/hive.py compile. Do not hand-edit. -->\nbundle content\n',
  );
  await writeFile(path.join(composableDir, 'VERSION'), opts.version ?? '1.0.0');

  const assetDirNames = Object.keys(opts.assetDirs ?? {}).sort();
  for (const dirName of assetDirNames) {
    const files = opts.assetDirs![dirName]!;
    const assetSrcDir = path.join(skillDir, 'assets-src', dirName);
    await mkdir(assetSrcDir, { recursive: true });
    for (const [relFile, content] of Object.entries(files)) {
      await mkdir(path.dirname(path.join(assetSrcDir, relFile)), { recursive: true });
      await writeFile(path.join(assetSrcDir, relFile), content);
    }
  }

  return {
    name: opts.name,
    category: opts.category,
    version: opts.version ?? '1.0.0',
    minis: 1,
    bundleTokens: 10,
    description: opts.description ?? 'A test skill.',
    path: `skills/${opts.category}/${opts.name}`,
    ...(assetDirNames.length > 0 ? { assetDirs: assetDirNames } : {}),
  };
}

async function makeCatalog(skillOpts: FixtureSkillOpts[]): Promise<Catalog> {
  const skills = [];
  for (const opts of skillOpts) skills.push(await writeFixtureSkill(opts));
  const manifest = {
    generatedAt: new Date(0).toISOString(),
    hiveCommit: 'test-commit',
    skills,
    files: [],
  };
  await writeFile(path.join(assetsDir, 'manifest.json'), JSON.stringify(manifest));
  return loadCatalog(assetsDir);
}

function ctx() {
  return resolveHomeContext({ homeFlag: homeDir, platform: 'linux' });
}

const alwaysConfirm: ExecutePorts = { confirmPointerWrite: async () => true };
const alwaysDecline: ExecutePorts = { confirmPointerWrite: async () => false };

async function hashWholeTree(dir: string): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  async function walk(current: string) {
    let entries;
    try {
      entries = await readdir(current, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const abs = path.join(current, entry.name);
      if (entry.isDirectory()) {
        await walk(abs);
      } else if (entry.isFile()) {
        out.set(path.relative(dir, abs), createHash('sha256').update(await readFile(abs)).digest('hex'));
      }
    }
  }
  await walk(dir);
  return out;
}

describe('renderSkillShim', () => {
  it('produces frontmatter with name/description and a coverage-rule body, under ~20 lines', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo', description: 'Does foo things.' }]);
    const skill = catalog.skills[0]!;
    const shim = renderSkillShim(skill);
    const lines = shim.split('\n');

    expect(lines[0]).toBe('---');
    expect(lines).toContain('name: hive-foo');
    expect(shim).toContain('description: Does foo things. Load composable/INDEX.md first.');
    expect(shim).toContain('composable/INDEX.md');
    expect(shim).toContain('60%');
    expect(shim).toContain('BUNDLE.md');
    expect(lines.length).toBeLessThanOrEqual(20);
  });
});

describe('planInstall', () => {
  it('throws UnknownClientError for an unregistered client id', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await expect(
      planInstall(ctx(), { clients: ['not-a-real-client'], skills: ['foo'], catalog }),
    ).rejects.toThrow(UnknownClientError);
  });

  it('throws UnknownSkillError for a skill not in the catalog', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await expect(
      planInstall(ctx(), { clients: ['claude-code'], skills: ['does-not-exist'], catalog }),
    ).rejects.toThrow(UnknownSkillError);
  });

  it('throws UnsupportedClientError listing every scan-only client requested', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await expect(
      planInstall(ctx(), { clients: ['roo', 'continue', 'claude-code'], skills: ['foo'], catalog }),
    ).rejects.toThrow(UnsupportedClientError);
    try {
      await planInstall(ctx(), { clients: ['roo', 'continue'], skills: ['foo'], catalog });
      throw new Error('expected to throw');
    } catch (err) {
      expect(err).toBeInstanceOf(UnsupportedClientError);
      expect((err as UnsupportedClientError).clientIds.sort()).toEqual(['continue', 'roo']);
    }
  });

  it('plans copy-tree + write-skill-shim + write-install-manifest for a native-skills client, no pointer action', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog });

    const kinds = plan.actions.map((a) => a.kind);
    expect(kinds).toEqual(['copy-tree', 'write-skill-shim', 'write-install-manifest']);
    const treeAction = plan.actions[0]!;
    expect(treeAction.kind).toBe('copy-tree');
    if (treeAction.kind === 'copy-tree' || treeAction.kind === 'upgrade') {
      expect(treeAction.destSkillDir).toBe(path.join(homeDir, '.claude', 'skills', 'hive-foo'));
    }
  });

  it('plans a payload tree + exactly ONE pointer-block action per client for a payload-pointer client (gemini), covering multiple skills', async () => {
    const catalog = await makeCatalog([
      { category: 'authored', name: 'foo' },
      { category: 'authored', name: 'bar' },
    ]);
    const plan = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo', 'bar'], catalog });

    const pointerActions = plan.actions.filter((a) => a.kind === 'write-pointer-block');
    expect(pointerActions.length).toBe(1);
    expect(pointerActions[0]).toMatchObject({
      clientId: 'gemini',
      destPath: path.join(homeDir, '.gemini', 'GEMINI.md'),
    });

    const treeActions = plan.actions.filter((a) => a.kind === 'copy-tree' || a.kind === 'upgrade');
    expect(treeActions.length).toBe(2);
    for (const action of treeActions) {
      if (action.kind === 'copy-tree' || action.kind === 'upgrade') {
        expect(action.destSkillDir.startsWith(path.join(homeDir, '.gemini', 'hive-skills'))).toBe(true);
      }
    }
  });

  it('cursor (payload-project-pointer) plans a project pointer only when projectDir is given', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);

    const withoutProject = await planInstall(ctx(), { clients: ['cursor'], skills: ['foo'], catalog });
    expect(withoutProject.actions.some((a) => a.kind === 'write-pointer-block')).toBe(false);
    expect(withoutProject.actions.some((a) => a.kind === 'copy-tree')).toBe(true);

    const projectDir = path.join(tmp, 'my-project');
    const withProject = await planInstall(ctx(), {
      clients: ['cursor'],
      skills: ['foo'],
      catalog,
      projectDir,
    });
    const pointerAction = withProject.actions.find((a) => a.kind === 'write-pointer-block');
    expect(pointerAction).toBeDefined();
    expect(pointerAction).toMatchObject({
      destPath: path.join(projectDir, '.cursor', 'rules', 'hive-skills.mdc'),
    });
  });
});

describe('executeInstall: dry-run', () => {
  it('performs zero filesystem writes and reports wouldWrite entries', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog });

    const before = await hashWholeTree(homeDir);
    const result = await executeInstall(ctx(), plan, alwaysConfirm, { dryRun: true });
    const after = await hashWholeTree(homeDir);

    expect(after).toEqual(before);
    expect(result.performed).toEqual([]);
    expect(result.backups).toEqual([]);
    expect(result.wouldWrite.length).toBe(3);
    expect(result.wouldWrite.map((w) => w.kind)).toEqual([
      'copy-tree',
      'write-skill-shim',
      'write-install-manifest',
    ]);
  });
});

describe('executeInstall: full installs', () => {
  it('installs a native-skills client (claude-code): composable tree, SKILL.md shim, .hive-install.json', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo', description: 'Foo skill.' }]);
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog });
    const result = await executeInstall(ctx(), plan, alwaysConfirm, {});

    expect(result.performed.length).toBe(3);
    expect(result.backups.length).toBe(1);

    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-foo');
    const indexContent = await readFile(path.join(destDir, 'composable', 'INDEX.md'), 'utf8');
    expect(indexContent).toContain('Foo skill.');

    const shim = await readFile(path.join(destDir, 'SKILL.md'), 'utf8');
    expect(shim).toContain('name: hive-foo');

    const manifest = await readInstallManifest(destDir);
    expect(manifest?.skillName).toBe('foo');
    expect(manifest?.skillVersion).toBe('1.0.0');
    expect(manifest?.treeSha256).toBe(await computeInstalledTreeHash(destDir));
  });

  it('installs codex (native-skills)', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const plan = await planInstall(ctx(), { clients: ['codex'], skills: ['foo'], catalog });
    const result = await executeInstall(ctx(), plan, alwaysConfirm, {});
    expect(result.performed.length).toBe(3);
    const destDir = path.join(homeDir, '.codex', 'skills', 'hive-foo');
    expect((await stat(destDir)).isDirectory()).toBe(true);
  });

  it('installs a payload+pointer client (gemini) and writes the pointer block on confirm=true', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await mkdir(path.join(homeDir, '.gemini'), { recursive: true });
    await writeFile(path.join(homeDir, '.gemini', 'GEMINI.md'), 'my existing rules\n');

    const plan = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo'], catalog });
    const result = await executeInstall(ctx(), plan, alwaysConfirm, {});

    const gemini = await readFile(path.join(homeDir, '.gemini', 'GEMINI.md'), 'utf8');
    expect(gemini).toContain('my existing rules');
    expect(gemini).toContain(MANAGED_BLOCK_START);
    expect(gemini).toContain(path.join(homeDir, '.gemini', 'hive-skills'));
    expect(result.performed.some((a) => a.kind === 'write-pointer-block')).toBe(true);

    const destDir = path.join(homeDir, '.gemini', 'hive-skills', 'hive-foo');
    expect((await stat(destDir)).isDirectory()).toBe(true);
  });

  it('declines the pointer write when confirmPointerWrite resolves false, still installs the tree', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const plan = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo'], catalog });
    const result = await executeInstall(ctx(), plan, alwaysDecline, {});

    expect(result.skipped.some((a) => a.kind === 'write-pointer-block')).toBe(true);
    expect(result.performed.some((a) => a.kind === 'write-pointer-block')).toBe(false);
    await expect(stat(path.join(homeDir, '.gemini', 'GEMINI.md'))).rejects.toThrow();

    const destDir = path.join(homeDir, '.gemini', 'hive-skills', 'hive-foo');
    expect((await stat(destDir)).isDirectory()).toBe(true);
  });

  it('cursor project pointer is written under the given projectDir', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const projectDir = path.join(tmp, 'my-project');
    const plan = await planInstall(ctx(), { clients: ['cursor'], skills: ['foo'], catalog, projectDir });
    const result = await executeInstall(ctx(), plan, alwaysConfirm, {});

    expect(result.performed.some((a) => a.kind === 'write-pointer-block')).toBe(true);
    const pointerFile = path.join(projectDir, '.cursor', 'rules', 'hive-skills.mdc');
    const content = await readFile(pointerFile, 'utf8');
    expect(content).toContain(MANAGED_BLOCK_START);
  });
});

describe('executeInstall: non-knowledge asset dirs (scripts/, etc.)', () => {
  it('materializes a bundled assets-src dir into the installed skill dir root', async () => {
    const catalog = await makeCatalog([
      {
        category: 'converted',
        name: 'pdf',
        assetDirs: { scripts: { 'check_fillable_fields.py': 'print("check")\n' } },
      },
    ]);
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['pdf'], catalog });
    await executeInstall(ctx(), plan, alwaysConfirm, {});

    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-pdf');
    const script = await readFile(path.join(destDir, 'scripts', 'check_fillable_fields.py'), 'utf8');
    expect(script).toBe('print("check")\n');
  });

  it('includes materialized asset files in the installed tree hash (post-install, drift-detectable)', async () => {
    const catalog = await makeCatalog([
      {
        category: 'converted',
        name: 'pdf',
        assetDirs: { scripts: { 'check_fillable_fields.py': 'print("check")\n' } },
      },
    ]);
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['pdf'], catalog });
    await executeInstall(ctx(), plan, alwaysConfirm, {});

    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-pdf');
    const manifest = await readInstallManifest(destDir);
    expect(manifest?.treeSha256).toBe(await computeInstalledTreeHash(destDir));
  });

  it('a second identical install (with assets) is skip-identical — plan-time hash matches post-install hash', async () => {
    const catalog = await makeCatalog([
      {
        category: 'converted',
        name: 'pdf',
        assetDirs: { scripts: { 'check_fillable_fields.py': 'print("check")\n' } },
      },
    ]);
    const plan1 = await planInstall(ctx(), { clients: ['claude-code'], skills: ['pdf'], catalog });
    await executeInstall(ctx(), plan1, alwaysConfirm, {});

    const plan2 = await planInstall(ctx(), { clients: ['claude-code'], skills: ['pdf'], catalog });
    expect(plan2.actions.map((a) => a.kind)).toEqual(['skip-identical']);
  });

  it('upgrades when only the asset file content changes (composable tree untouched)', async () => {
    const catalog1 = await makeCatalog([
      {
        category: 'converted',
        name: 'pdf',
        assetDirs: { scripts: { 'check_fillable_fields.py': 'v1\n' } },
      },
    ]);
    const plan1 = await planInstall(ctx(), { clients: ['claude-code'], skills: ['pdf'], catalog: catalog1 });
    await executeInstall(ctx(), plan1, alwaysConfirm, {});

    const catalog2 = await makeCatalog([
      {
        category: 'converted',
        name: 'pdf',
        assetDirs: { scripts: { 'check_fillable_fields.py': 'v2\n' } },
      },
    ]);
    const plan2 = await planInstall(ctx(), { clients: ['claude-code'], skills: ['pdf'], catalog: catalog2 });
    expect(plan2.actions.map((a) => a.kind)).toEqual(['upgrade', 'write-skill-shim', 'write-install-manifest']);

    await executeInstall(ctx(), plan2, alwaysConfirm, {});
    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-pdf');
    const script = await readFile(path.join(destDir, 'scripts', 'check_fillable_fields.py'), 'utf8');
    expect(script).toBe('v2\n');
  });

  it('a skill with no assetDirs installs exactly as before (no assets-src copy step, no extra dirs)', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog });
    await executeInstall(ctx(), plan, alwaysConfirm, {});

    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-foo');
    const entries = await readdir(destDir);
    expect(entries.sort()).toEqual(['.hive-install.json', 'SKILL.md', 'composable'].sort());
  });
});

describe('executeInstall: idempotency', () => {
  it('a second identical install run reports all skip-identical and does not re-prompt for an unchanged pointer', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    let confirmCalls = 0;
    const countingPorts: ExecutePorts = {
      confirmPointerWrite: async () => {
        confirmCalls++;
        return true;
      },
    };

    const plan1 = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo'], catalog });
    await executeInstall(ctx(), plan1, countingPorts, {});
    expect(confirmCalls).toBe(1);

    const plan2 = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo'], catalog });
    expect(plan2.actions.filter((a) => a.kind === 'skip-identical').length).toBe(1);
    expect(plan2.actions.some((a) => a.kind === 'copy-tree' || a.kind === 'upgrade')).toBe(false);

    const result2 = await executeInstall(ctx(), plan2, countingPorts, {});
    expect(confirmCalls).toBe(1); // unchanged pointer content -> no re-prompt
    expect(result2.skipped.some((a) => a.kind === 'skip-identical')).toBe(true);
    expect(result2.performed).toEqual([]);
  });

  it('upgrades when the bundled asset changes: new content installed, manifest updated', async () => {
    const catalog1 = await makeCatalog([{ category: 'authored', name: 'foo', version: '1.0.0', coreContent: 'v1' }]);
    const plan1 = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog: catalog1 });
    await executeInstall(ctx(), plan1, alwaysConfirm, {});

    // Mutate the bundled asset + regenerate the catalog to reflect a new version.
    const catalog2 = await makeCatalog([{ category: 'authored', name: 'foo', version: '1.1.0', coreContent: 'v2' }]);
    const plan2 = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog: catalog2 });

    expect(plan2.actions.map((a) => a.kind)).toEqual(['upgrade', 'write-skill-shim', 'write-install-manifest']);

    const result2 = await executeInstall(ctx(), plan2, alwaysConfirm, {});
    expect(result2.performed.length).toBe(3);

    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-foo');
    const coreContent = await readFile(path.join(destDir, 'composable', 'mini', '00-core.md'), 'utf8');
    expect(coreContent).toBe('v2');
    const manifest = await readInstallManifest(destDir);
    expect(manifest?.skillVersion).toBe('1.1.0');
  });
});

describe('executeInstall: uninstall via restore', () => {
  it('restoring the preinstall backup removes a freshly-installed skill tree and leaves the freshly-created pointer block untouched', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const plan = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo'], catalog });
    const result = await executeInstall(ctx(), plan, alwaysConfirm, {});

    expect(result.backups.length).toBe(1);
    const backupId = result.backups[0]!.id;

    const destDir = path.join(homeDir, '.gemini', 'hive-skills', 'hive-foo');
    const pointerFile = path.join(homeDir, '.gemini', 'GEMINI.md');
    await expect(stat(destDir)).resolves.toBeTruthy();
    const pointerBefore = await readFile(pointerFile, 'utf8');
    expect(pointerBefore).toContain(MANAGED_BLOCK_START);

    await restore(ctx(), backupId, {});

    // Skill tree gone (uninstalled).
    await expect(stat(destDir)).rejects.toThrow();
    // Pointer file untouched: the managed block this install created is
    // NOT auto-removed by restore(), because a not-yet-existing pointer
    // file is deliberately excluded from the preinstall backup (see
    // installer.ts's comment) — restore() never learns about this path
    // and so cannot revert/delete it. This is a documented limitation:
    // a pointer file that pre-existed before install WOULD be captured
    // by the backup and would be fully reverted (block included) by this
    // same restore() call, since backup.ts's restore() has no concept of
    // a managed block (see its own TODO comment).
    const pointerAfter = await readFile(pointerFile, 'utf8');
    expect(pointerAfter).toBe(pointerBefore);
    expect(pointerAfter).toContain(MANAGED_BLOCK_START);
  });

  it('documents the limitation: a pre-existing pointer file IS captured and fully reverted by restore (block removed)', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    await mkdir(path.join(homeDir, '.gemini'), { recursive: true });
    await writeFile(path.join(homeDir, '.gemini', 'GEMINI.md'), 'pre-existing rules only\n');

    const plan = await planInstall(ctx(), { clients: ['gemini'], skills: ['foo'], catalog });
    const result = await executeInstall(ctx(), plan, alwaysConfirm, {});
    const backupId = result.backups[0]!.id;

    const pointerFile = path.join(homeDir, '.gemini', 'GEMINI.md');
    expect(await readFile(pointerFile, 'utf8')).toContain(MANAGED_BLOCK_START);

    await restore(ctx(), backupId, {});

    // Known limitation (see backup.ts's restore() TODO): restore is
    // block-unaware, so a pre-existing pointer file is fully reverted,
    // removing the block along with anything else that changed.
    expect(await readFile(pointerFile, 'utf8')).toBe('pre-existing rules only\n');
  });
});

describe('executeInstall: pre-flight foreign-directory refusal', () => {
  it('refuses to overwrite a non-Hive directory occupying the install path without force', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-foo');
    await mkdir(destDir, { recursive: true });
    await writeFile(path.join(destDir, 'unrelated.txt'), 'not ours');

    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog });
    await expect(executeInstall(ctx(), plan, alwaysConfirm, {})).rejects.toThrow(/force/);

    // Untouched.
    expect(await readFile(path.join(destDir, 'unrelated.txt'), 'utf8')).toBe('not ours');

    const result = await executeInstall(ctx(), plan, alwaysConfirm, { force: true });
    expect(result.performed.length).toBeGreaterThan(0);
  });
});

// Sanity: exercise every registry-declared install-eligible strategy at
// least once, so a future registry change that breaks resolution here
// (e.g. a typo in payloadPath) fails loudly.
describe('registry coverage', () => {
  it('every non-scan-only client id resolves to a valid plan', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const installable = CLIENT_REGISTRY.filter((e) => e.strategy !== 'scan-only');
    expect(installable.length).toBeGreaterThan(0);
    for (const entry of installable) {
      const projectDir = entry.strategy === 'payload-project-pointer' ? path.join(tmp, 'proj') : undefined;
      const plan = await planInstall(ctx(), { clients: [entry.id], skills: ['foo'], catalog, projectDir });
      expect(plan.actions.length).toBeGreaterThan(0);
    }
  });
});

