import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { resolveHomeContext } from '../src/core/paths.js';
import { CLIENT_REGISTRY } from '../src/core/registry.js';
import { loadCatalog, type Catalog } from '../src/core/catalog.js';
import { MANAGED_BLOCK_START } from '../src/core/pointer.js';
import {
  WIZARD_CANCEL,
  runWizard,
  type Cancelable,
  type WizardDeps,
  type WizardPorts,
} from '../src/wizard.js';

let tmp: string;
let homeDir: string;
let assetsDir: string;

beforeEach(async () => {
  tmp = await mkdtemp(path.join(os.tmpdir(), 'hive-wizard-'));
  homeDir = path.join(tmp, 'home');
  assetsDir = path.join(tmp, 'assets');
  await mkdir(homeDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });
});

afterEach(async () => {
  await rm(tmp, { recursive: true, force: true });
});

function ctx() {
  return resolveHomeContext({ homeFlag: homeDir, platform: 'linux' });
}

async function makeCatalog(
  skillOpts: Array<{ category: string; name: string; bundleTokens?: number }>,
): Promise<Catalog> {
  const skills = [];
  for (const opts of skillOpts) {
    const composableDir = path.join(assetsDir, 'skills', opts.category, opts.name, 'composable');
    await mkdir(path.join(composableDir, 'mini'), { recursive: true });
    await writeFile(path.join(composableDir, 'INDEX.md'), `# ${opts.name}\n\nA test skill.\n`);
    await writeFile(path.join(composableDir, 'mini', '00-core.md'), 'core content');
    await writeFile(
      path.join(composableDir, 'BUNDLE.md'),
      '<!-- GENERATED by tools/hive.py compile. Do not hand-edit. -->\nbundle\n',
    );
    await writeFile(path.join(composableDir, 'VERSION'), '1.0.0');
    skills.push({
      name: opts.name,
      category: opts.category,
      version: '1.0.0',
      minis: 1,
      // Default well ABOVE packing.ts's DEFAULT_INLINE_THRESHOLD (25_000):
      // runWizard defaults planInstall's packing to 'auto', and every
      // existing test in this file below is exercising wizard MECHANICS
      // (prompts/cancellation/confirm flow), not packing-mode selection —
      // keeping these fixtures tree-sized preserves their original
      // tree-shape assertions unchanged. The dedicated
      // "runWizard: bundle-inline packing" block below overrides this to
      // cover the inline path explicitly.
      bundleTokens: opts.bundleTokens ?? 30_000,
      description: 'A test skill.',
      sourceDescription: 'A test skill.',
      descriptionSource: 'index-fallback' as const,
      path: `skills/${opts.category}/${opts.name}`,
    });
  }
  await writeFile(
    path.join(assetsDir, 'manifest.json'),
    JSON.stringify({ generatedAt: new Date(0).toISOString(), hiveCommit: 'test', skills, files: [] }),
  );
  return loadCatalog(assetsDir);
}

interface MockPortsOptions {
  multiselect?: Array<Cancelable<string[]>>;
  select?: Array<Cancelable<string>>;
  confirm?: Array<Cancelable<boolean>>;
}

interface MockCalls {
  intro: string[];
  outro: string[];
  note: Array<{ message: string; title?: string }>;
  spinnerStart: string[];
  spinnerStop: string[];
  multiselectCount: number;
  selectCount: number;
  confirmCount: number;
}

function makeMockPorts(opts: MockPortsOptions): { ports: WizardPorts; calls: MockCalls } {
  const calls: MockCalls = {
    intro: [],
    outro: [],
    note: [],
    spinnerStart: [],
    spinnerStop: [],
    multiselectCount: 0,
    selectCount: 0,
    confirmCount: 0,
  };
  const ports: WizardPorts = {
    intro: (m) => calls.intro.push(m),
    outro: (m) => calls.outro.push(m),
    note: (m, t) => calls.note.push({ message: m, title: t }),
    spinnerStart: (m) => calls.spinnerStart.push(m),
    spinnerStop: (m) => calls.spinnerStop.push(m),
    multiselect: async () => {
      const response = (opts.multiselect ?? [])[calls.multiselectCount];
      calls.multiselectCount++;
      return (response ?? []) as never;
    },
    select: async () => {
      const response = (opts.select ?? [])[calls.selectCount];
      calls.selectCount++;
      return response as never;
    },
    confirm: async () => {
      const response = (opts.confirm ?? [])[calls.confirmCount];
      calls.confirmCount++;
      return response as never;
    },
  };
  return { ports, calls };
}

function deps(catalog: Catalog, extra: Partial<WizardDeps> = {}): WizardDeps {
  return { ctx: ctx(), registry: CLIENT_REGISTRY, catalog, ...extra };
}

describe('runWizard: no clients detected', () => {
  it('exits cleanly when nothing is detected', async () => {
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports, calls } = makeMockPorts({});
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'no-clients-detected' });
    expect(calls.outro[0]).toContain('Nothing to do');
  });
});

describe('runWizard: cancellation at each step', () => {
  it('cancels at the client multiselect', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports, calls } = makeMockPorts({ multiselect: [WIZARD_CANCEL] });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'cancelled' });
    expect(calls.outro[0]).toContain('Cancelled');
  });

  it('cancels at the skill multiselect', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({ multiselect: [['claude-code'], WIZARD_CANCEL] });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'cancelled' });
  });

  it('cancels at the action select', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: [WIZARD_CANCEL],
    });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'cancelled' });
  });

  it('cancels at the install plan confirm', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['install'],
      confirm: [WIZARD_CANCEL],
    });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'cancelled' });
    await expect(stat(path.join(homeDir, '.claude', 'skills', 'hive-foo'))).rejects.toThrow();
  });

  it('declining (not cancelling) the plan confirm also writes nothing', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['install'],
      confirm: [false],
    });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'declined-plan' });
    await expect(stat(path.join(homeDir, '.claude', 'skills', 'hive-foo'))).rejects.toThrow();
  });
});

describe('runWizard: empty selections', () => {
  it('empty client selection exits cleanly', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({ multiselect: [[]] });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'no-clients-selected' });
  });

  it('empty skill selection exits cleanly', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({ multiselect: [['claude-code'], []] });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'no-skills-selected' });
  });
});

describe('runWizard: install action, full happy path', () => {
  it('installs for a native-skills client on confirm=true', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports, calls } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['install'],
      confirm: [true],
    });

    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome.outcome).toBe('installed');
    if (outcome.outcome === 'installed') {
      expect(outcome.result.performed.length).toBe(3);
      expect(outcome.result.backups.length).toBe(1);
    }
    expect((await stat(path.join(homeDir, '.claude', 'skills', 'hive-foo'))).isDirectory()).toBe(true);
    expect(calls.outro.some((m) => m.includes('Installed'))).toBe(true);
  });

  it('marks scan-only detected clients disabled in the client multiselect options', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    await mkdir(path.join(homeDir, '.continue'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);

    let seenOptions: unknown;
    const ports: WizardPorts = {
      intro: () => {},
      outro: () => {},
      note: () => {},
      spinnerStart: () => {},
      spinnerStop: () => {},
      multiselect: async (args) => {
        seenOptions = args.options;
        return WIZARD_CANCEL;
      },
      select: async () => WIZARD_CANCEL,
      confirm: async () => WIZARD_CANCEL,
    };

    await runWizard(deps(catalog), ports);
    const options = seenOptions as Array<{ value: string; disabled?: boolean }>;
    const continueOpt = options.find((o) => o.value === 'continue');
    const claudeOpt = options.find((o) => o.value === 'claude-code');
    expect(continueOpt?.disabled).toBe(true);
    expect(claudeOpt?.disabled).toBeFalsy();
  });

  it('routes each pointer write through ports.confirm, showing the diff via ports.note', async () => {
    await mkdir(path.join(homeDir, '.gemini'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports, calls } = makeMockPorts({
      multiselect: [['gemini'], ['foo']],
      select: ['install'],
      confirm: [true, true], // plan confirm, then pointer-write confirm
    });

    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome.outcome).toBe('installed');
    const gemini = await readFile(path.join(homeDir, '.gemini', 'GEMINI.md'), 'utf8');
    expect(gemini).toContain(MANAGED_BLOCK_START);
    expect(calls.note.some((n) => n.title?.startsWith('Pointer write'))).toBe(true);
  });

  it('reports nothing-to-do when the plan resolves empty (already installed)', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);

    // First install, for real, outside the wizard.
    const { planInstall, executeInstall } = await import('../src/core/installer.js');
    const plan = await planInstall(ctx(), { clients: ['claude-code'], skills: ['foo'], catalog });
    await executeInstall(ctx(), plan, { confirmPointerWrite: async () => true }, {});

    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['install'],
    });
    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'declined-plan' });
  });
});

describe('runWizard: propose action', () => {
  it('writes a conversion-proposal doc to the current working directory', async () => {
    await mkdir(path.join(homeDir, '.claude', 'skills', 'my-rule'), { recursive: true });
    await writeFile(path.join(homeDir, '.claude', 'skills', 'my-rule', 'x.md'), 'x'.repeat(21000));

    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['propose'],
    });

    const outDir = path.join(tmp, 'cwd');
    await mkdir(outDir, { recursive: true });
    const originalCwd = process.cwd();
    process.chdir(outDir);
    try {
      const outcome = await runWizard(deps(catalog, { now: () => '2026-01-01T00:00:00.000Z' }), ports);
      expect(outcome.outcome).toBe('proposed');
      if (outcome.outcome === 'proposed') {
        expect(outcome.candidates.length).toBeGreaterThan(0);
        const doc = await readFile(outcome.outPath, 'utf8');
        expect(doc).toContain('Hive Conversion Proposals');
      }
    } finally {
      process.chdir(originalCwd);
    }
  });
});

describe('runWizard: backup action', () => {
  it('snapshots the selected clients\' existing state', async () => {
    await mkdir(path.join(homeDir, '.claude', 'skills', 'hive-foo'), { recursive: true });
    await writeFile(path.join(homeDir, '.claude', 'skills', 'hive-foo', 'SKILL.md'), 'x'.repeat(20));

    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['backup'],
    });

    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'backed-up', clientIds: ['claude-code'] });

    const { listBackups } = await import('../src/core/backup.js');
    const backups = await listBackups(ctx());
    expect(backups.length).toBe(1);
  });
});

describe('runWizard: doctor action', () => {
  it('runs doctor and shows the report via ports.note', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'authored', name: 'foo' }]);
    const { ports, calls } = makeMockPorts({
      multiselect: [['claude-code'], ['foo']],
      select: ['doctor'],
    });

    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome).toEqual({ outcome: 'doctor-run' });
    expect(calls.note.some((n) => n.title === 'Doctor report')).toBe(true);
  });
});

describe('runWizard: bundle-inline packing (docs/packing-modes.md — wizard defaults to "auto" like the CLI)', () => {
  it('installs a small skill bundle-inline (no composable/ dir, SKILL.md carries the bundle)', async () => {
    await mkdir(path.join(homeDir, '.claude'), { recursive: true });
    const catalog = await makeCatalog([{ category: 'converted', name: 'pdf', bundleTokens: 5_000 }]);
    const { ports } = makeMockPorts({
      multiselect: [['claude-code'], ['pdf']],
      select: ['install'],
      confirm: [true],
    });

    const outcome = await runWizard(deps(catalog), ports);
    expect(outcome.outcome).toBe('installed');
    if (outcome.outcome === 'installed') {
      expect(outcome.result.performed.length).toBe(2); // write-inline-skill + write-install-manifest, no shim
    }

    const destDir = path.join(homeDir, '.claude', 'skills', 'hive-pdf');
    await expect(stat(path.join(destDir, 'composable'))).rejects.toThrow();
    const skillMd = await readFile(path.join(destDir, 'SKILL.md'), 'utf8');
    expect(skillMd).toContain('bundle');
  });
});
