/**
 * The comment `tools/hive.py compile` stamps at the top of every
 * generated `BUNDLE.md` (do-not-hand-edit marker). Shared by doctor.ts
 * (detects a hand-edited/corrupt BUNDLE.md) and installer.ts (strips it
 * before embedding the bundle body in an inline SKILL.md, and before
 * counting bundleTokens for the packing-mode size rule — packing-modes.md
 * v2 item 6: "same accounting as the catalog's bundleTokens"). Also
 * duplicated (independently, as a plain string literal) in
 * scripts/bundle-assets.mjs, which can't import this compiled TS module
 * at pre-build time — same rationale doctor.ts's own copy used to carry
 * before this module existed.
 */
export const BUNDLE_GENERATED_MARKER = '<!-- GENERATED by tools/hive.py compile. Do not hand-edit. -->';

/** `bundleRaw` with every line that is exactly the generated marker removed. */
export function stripGeneratedMarker(bundleRaw: string): string {
  return bundleRaw
    .split('\n')
    .filter((line) => line.trim() !== BUNDLE_GENERATED_MARKER)
    .join('\n');
}
